version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/node:14.15'
    steps:
      # install node and checkout code
      - checkout
      - node/install:
          node-version: '14.15'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      # TODO: Install dependencies in the the backend API
      - run:
          name: Install API Dependencies
          command: |
            echo "TODO: Install dependencies in the the backend API"
            npm run api:install

      # TODO: Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            echo "TODO: Lint the frontend"
            npm run frontend:lint

      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "TODO: Build the frontend app"
            npm run frontend:build

      # TODO: Build the backend API
      - run:
          name: API Build
          command: |
            echo "TODO: Build the backend API"
            npm run api:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: 'cimg/base:stable'
      - image: circleci/python:3.7.3
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - aws-cli/install
      - node/install:
          node-version: '14.15'
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: Install EB CLI
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip -y
            sudo pip3 install --upgrade pip
            sudo pip3 install awsebcli
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Set environment variables
          command: |
            export POSTGRES_USERNAME=$POSTGRES_USERNAME
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            export POSTGRES_HOST=$POSTGRES_HOST
            export POSTGRES_DB=$POSTGRES_DB
            export DB_PORT=$DB_PORT
            export AWS_BUCKET=$AWS_BUCKET
            export AWS_REGION=$AWS_REGION
            export AWS_PROFILE=$AWS_PROFILE
            export JWT_SECRET=$JWT_SECRET
            export URL=$JWT_SECRET
            export PORT=$PORT
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb init udagram-api --region $AWS_DEFAULT_REGION --platform "Node.js 14 running on 64bit Amazon Linux 2"
            npm run deploy
            eb use udagram-api-test
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_HOST=$POSTGRES_HOST POSTGRES_DB=$POSTGRES_DB DB_PORT=$DB_PORT AWS_BUCKET=$AWS_BUCKET AWS_REGION=$AWS_REGION JWT_SECRET=$JWT_SECRET URL=$URL PORT=$PORT AWS_PROFILE=$AWS_PROFILE
            prefix="v1.0."
            timestamp=$(date +'%Y%m%d%H%M%S')
            versionLabel="$prefix$timestamp"
            cd "./udagram/udagram-api/"
            eb deploy udagram-api-test --label $versionLabel

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
